import { ArrowRight, ArrowDownRight, ChevronRight, CircleUserRound, MoveUpRight } from "lucide-react";
import { capabilities, delivery, sessions } from "./components/community-data";
import { CommunityChrome } from "./components/community-chrome";

export default function CommunityHome() {
  return (
    <CommunityChrome>
      <section className="hero-band section-wide" id="top">
        <div className="hero-band-inner section">
          <div className="hero-copy"><p className="eyebrow hero-eyebrow"><span className="eyebrow-line" /> PRODUCTION-MINDED PEOPLE</p><h1>Build What<br /><span>Holds</span> <em>Up.</em></h1><p className="hero-lede">A technical community for people building secure platforms, resilient infrastructure, practical AI, and products that last.</p><div className="hero-actions"><a className="button button-primary" href="/capabilities">EXPLORE CAPABILITIES <ArrowRight size={17} /></a><a className="text-link text-link-on-dark" href="/delivery">OUR APPROACH <MoveUpRight size={15} /></a></div><div className="hero-meta"><span>ISLAMABAD / GLOBAL</span><span className="meta-rule" /><span>ENGINEERING IN MOTION</span></div></div>
          <div className="hero-art" role="img" aria-label="Abstract geometric composition in the community colour system"><div className="art-grid" aria-hidden="true" /><div className="art-circle art-circle-one" aria-hidden="true" /><div className="art-circle art-circle-two" aria-hidden="true" /><div className="art-core" aria-hidden="true"><span>C</span></div><div className="art-label art-label-top"><span className="art-label-dot" /> WEB / SECURITY / AI / CLOUD</div><div className="art-label art-label-bottom">SECURITY FIRST<br />BUILT TO LAST</div><span className="art-coordinate">SYSTEMS THAT SCALE<br />PEOPLE WHO SHARE</span></div>
        </div>
      </section>

      <section className="signal-strip section"><div className="signal-cell"><span className="signal-number">01</span><span>SHARE THE HARD QUESTION</span></div><div className="signal-cell"><span className="signal-number">02</span><span>MAKE THE TRADE-OFF VISIBLE</span></div><div className="signal-cell"><span className="signal-number">03</span><span>LEAVE WITH A CLEARER NEXT STEP</span></div></section>

      <section className="statement section" id="approach"><div className="section-number">01</div><div className="statement-heading"><p className="eyebrow">THE IDEA</p><h2>Security<br /><em>From Day One.</em></h2></div><div className="statement-copy"><p>The strongest systems bring architecture, security, infrastructure, and experience into the same conversation before the first feature ships.</p><p>That is the standard behind this community: direct thinking, practical lessons, and room for people doing the work to compare notes without the theatre.</p></div></section>

      <section className="capabilities section"><div className="section-heading"><div><p className="eyebrow">THE WORK AROUND THE WORK</p><h2>Five Ways<br />to <em>Contribute.</em></h2></div><p className="section-note">Choose the conversation closest to the work in front of you, then move across the system when the problem demands it.</p></div><div className="capability-grid">{capabilities.slice(0, 3).map((capability) => { const Icon = capability.icon; return <a className="capability-card" href="/capabilities" key={capability.title}><div className="capability-top"><span className="space-index">{capability.index}</span><span className="space-icon"><Icon size={19} strokeWidth={1.6} /></span></div><div className="capability-copy"><p className="card-label">{capability.label}</p><h3>{capability.title}</h3><p>{capability.description}</p></div><span className="capability-arrow"><ArrowDownRight size={18} /></span></a>; })}</div><a className="text-link home-section-link" href="/capabilities">VIEW ALL CAPABILITIES <MoveUpRight size={15} /></a></section>

      <section className="delivery section"><div className="section-heading"><div><p className="eyebrow">A CLEAR PROCESS</p><h2>From First<br /><em>Question.</em></h2></div><p className="section-note">The work gets stronger when scope, risk, and milestones are visible from the beginning.</p></div><div className="delivery-grid">{delivery.map((step) => <article className="delivery-card" key={step.title}><span className="delivery-number">{step.index}</span><h3>{step.title}</h3><p>{step.text}</p><span className="delivery-rule" /></article>)}</div></section>

      <section className="moments section"><div className="section-heading moments-heading"><div><p className="eyebrow">KEEP A DATE</p><h2>Upcoming<br /><em>Sessions.</em></h2></div><a className="text-link" href="/sessions">VIEW ALL <MoveUpRight size={15} /></a></div><div className="moment-list">{sessions.slice(0, 3).map((session, index) => <a className="moment-row" href="/sessions" key={session.title}><span className="moment-index">0{index + 1}</span><span className="moment-date">{session.date}</span><span className="moment-title">{session.title}</span><span className="moment-type">{session.type}</span><ChevronRight className="moment-arrow" size={19} /></a>)}</div></section>

      <section className="join-band section-wide"><div className="join section"><div className="join-rings" aria-hidden="true"><span /><span /><span /></div><div className="join-content"><p className="eyebrow light"><span className="eyebrow-line" /> YOUR NEXT MOVE</p><h2>Build With<br /><em>Intention.</em></h2><p>Get occasional notes about secure engineering, useful automation, resilient cloud systems, and community sessions.</p><a className="button button-primary" href="/join">JOIN THE GRID <ArrowRight size={17} /></a></div><div className="join-spec"><span className="join-spec-label">COMMUNITY / SYSTEMS 001</span><CircleUserRound size={82} strokeWidth={.7} /><span className="join-spec-copy">EVERY VOICE<br />CHANGES THE SHAPE.</span></div></div></section>
    </CommunityChrome>
  );
}
