"use client";

import Link from "next/link";
import { useState } from "react";
import { ArrowLeft, ArrowRight, Bookmark, CheckCircle2, Heart, MessageCircle, Send, Share2 } from "lucide-react";
import { communityPosts, type CommunityPost } from "@/data/community";

const replies = [
  { initials: "SA", name: "Sara Ahmed", role: "Design technologist", time: "Apr 02, 2026", body: "The idea of making the review ritual small enough to repeat is the part I am taking away. Security guidance is only useful when it survives a busy week." },
  { initials: "LM", name: "Leo Martins", role: "Cloud architect", time: "Apr 03, 2026", body: "Would love to see the threat-model template you used. We have been trying to keep it close to the pull request without making the PR unreadable." },
  { initials: "AK", name: "Ayesha Khan", role: "Product engineer", time: "Apr 04, 2026", body: "Absolutely. I added a lightweight version below the post. The key is to record the decision and the residual risk, not produce a perfect document." },
];

function SmallAvatar({ initials }: { initials: string }) {
  return <span className="inline-flex h-10 w-10 shrink-0 items-center justify-center rounded-full bg-[#1c69d4] font-mono text-[10px] font-bold text-white">{initials}</span>;
}

export default function CommunityPostView({ post }: { post: CommunityPost }) {
  const [liked, setLiked] = useState(false);
  const [saved, setSaved] = useState(false);
  const [comment, setComment] = useState("");
  const [commentSent, setCommentSent] = useState(false);
  const related = communityPosts.filter((item) => item.slug !== post.slug).slice(0, 2);

  return (
    <main className="bg-black text-white">
      <div className="m-stripe" aria-hidden="true" />
      <div className="mx-auto max-w-[1440px] px-5 py-12 sm:px-8 sm:py-20 lg:px-12">
        <Link href="/community" className="inline-flex min-h-11 items-center gap-2 font-mono text-[10px] font-bold uppercase tracking-[0.14em] text-[#bbbbbb] transition hover:text-white focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-white"><ArrowLeft className="h-3.5 w-3.5" aria-hidden /> Back to community</Link>
        <div className="mt-12 grid gap-16 lg:grid-cols-[minmax(0,820px)_300px] lg:gap-24">
          <article>
            <div className="flex flex-wrap items-center gap-3 font-mono text-[10px] font-bold uppercase tracking-[0.14em] text-[#8fc1ff]"><span>{post.category}</span><span className="text-[#7e7e7e]">/</span><span className="text-[#bbbbbb]">{post.time}</span><span className="text-[#7e7e7e]">/</span><span className="text-[#7e7e7e]">{post.readTime}</span>{post.solved ? <span className="inline-flex items-center gap-1 border border-[#0fa336] px-2 py-1 text-[#0fa336]"><CheckCircle2 className="h-3 w-3" aria-hidden /> Solved</span> : null}</div>
            <h1 className="mt-6 max-w-4xl text-[clamp(2.5rem,6vw,5.5rem)] font-bold uppercase leading-[0.94] tracking-[-0.04em] text-white">{post.title}</h1>
            <div className="mt-8 flex items-center gap-3 border-b border-[#3c3c3c] pb-8"><SmallAvatar initials={post.initials} /><div><p className="text-sm font-semibold text-white">{post.author}</p><p className="mt-1 text-xs font-light text-[#bbbbbb]">{post.role}</p></div></div>
            <div className="mt-10 max-w-3xl space-y-6 text-base font-light leading-8 text-[#bbbbbb]"><p className="text-lg leading-8 text-[#e6e6e6]">{post.excerpt}</p>{post.body.map((paragraph) => <p key={paragraph}>{paragraph}</p>)}{post.quote ? <blockquote className="border-l-2 border-[#1c69d4] bg-[#0d0d0d] px-6 py-5 text-xl leading-8 text-white">“{post.quote}”</blockquote> : null}<p>Use the replies to add examples, challenge assumptions, or share a different route. Keep client information and credentials out of the thread so the room stays safe for everyone.</p></div>
            <div className="mt-10 flex flex-wrap items-center gap-2 border-y border-[#3c3c3c] py-4"><button type="button" onClick={() => setLiked((value) => !value)} className={`inline-flex min-h-11 items-center gap-2 border px-3 text-xs transition focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-white ${liked ? "border-[#e22718] text-[#e22718]" : "border-[#3c3c3c] text-[#bbbbbb] hover:border-[#e22718] hover:text-[#e22718]"}`}><Heart className="h-4 w-4" fill={liked ? "currentColor" : "none"} aria-hidden /> {post.likes + (liked ? 1 : 0)}</button><button type="button" onClick={() => setSaved((value) => !value)} className={`inline-flex min-h-11 items-center gap-2 border px-3 text-xs transition focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-white ${saved ? "border-[#1c69d4] text-[#8fc1ff]" : "border-[#3c3c3c] text-[#bbbbbb] hover:border-white hover:text-white"}`}><Bookmark className="h-4 w-4" fill={saved ? "currentColor" : "none"} aria-hidden /> {saved ? "Saved" : "Save"}</button><button type="button" className="inline-flex min-h-11 items-center gap-2 border border-[#3c3c3c] px-3 text-xs text-[#bbbbbb] transition hover:border-white hover:text-white focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-white"><Share2 className="h-4 w-4" aria-hidden /> Share</button><span className="ml-auto hidden items-center gap-2 text-xs text-[#7e7e7e] sm:inline-flex"><MessageCircle className="h-4 w-4" aria-hidden /> {post.replies} replies</span></div>
            <section id="replies" className="mt-16 scroll-mt-24"><div className="flex items-center justify-between"><div><p className="font-mono text-[10px] font-bold uppercase tracking-[0.15em] text-[#8fc1ff]">The room responds</p><h2 className="mt-3 text-3xl font-bold uppercase tracking-[-0.03em] text-white">{post.replies} replies</h2></div><MessageCircle className="h-5 w-5 text-[#7e7e7e]" aria-hidden /></div><div className="mt-8 space-y-8">{replies.map((reply) => <div key={`${reply.name}-${reply.time}`} className="flex gap-4 border-b border-[#3c3c3c] pb-8"><SmallAvatar initials={reply.initials} /><div><div className="flex flex-wrap items-baseline gap-x-3 gap-y-1"><span className="text-sm font-semibold text-white">{reply.name}</span><span className="text-xs font-light text-[#bbbbbb]">{reply.role}</span><span className="font-mono text-[10px] uppercase tracking-[0.08em] text-[#7e7e7e]">{reply.time}</span></div><p className="mt-3 text-sm font-light leading-6 text-[#bbbbbb]">{reply.body}</p></div></div>)}</div><form className="mt-10 border border-[#3c3c3c] bg-[#1a1a1a] p-5" onSubmit={(event) => { event.preventDefault(); if (comment.trim()) { setCommentSent(true); setComment(""); } }}><label htmlFor="reply" className="font-mono text-[10px] font-bold uppercase tracking-[0.14em] text-[#bbbbbb]">Add to the conversation</label><div className="mt-4 flex flex-col gap-3 sm:flex-row"><textarea id="reply" value={comment} onChange={(event) => { setCommentSent(false); setComment(event.target.value); }} rows={3} placeholder="Share a useful perspective..." className="min-h-[76px] flex-1 resize-y border border-[#3c3c3c] bg-[#0d0d0d] px-4 py-3 text-sm font-light leading-6 text-white outline-none placeholder:text-[#7e7e7e] focus:border-white" /><button type="submit" className="inline-flex min-h-12 items-center justify-center gap-2 border border-white bg-black px-5 font-mono text-[10px] font-bold uppercase tracking-[0.14em] text-white transition hover:bg-white hover:text-black focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-white sm:self-end"><Send className="h-3.5 w-3.5" aria-hidden /> Reply</button></div>{commentSent ? <p className="mt-3 text-xs text-[#0fa336]">Your reply is saved as a draft for this preview.</p> : null}</form></section>
          </article>
          <aside className="space-y-12 lg:pt-28"><div className="border border-[#3c3c3c] bg-[#1a1a1a] p-6"><p className="font-mono text-[10px] font-bold uppercase tracking-[0.15em] text-[#8fc1ff]">In this thread</p><div className="mt-6 space-y-5 text-sm"><div className="flex items-center justify-between border-t border-[#3c3c3c] pt-4"><span className="font-light text-[#bbbbbb]">Reads</span><span className="font-mono text-xs text-white">{post.views.toLocaleString()}</span></div><div className="flex items-center justify-between border-t border-[#3c3c3c] pt-4"><span className="font-light text-[#bbbbbb]">Replies</span><span className="font-mono text-xs text-white">{post.replies}</span></div><div className="flex items-center justify-between border-t border-[#3c3c3c] pt-4"><span className="font-light text-[#bbbbbb]">Published</span><span className="max-w-[150px] text-right text-xs text-white">{post.time}</span></div></div></div><div><p className="font-mono text-[10px] font-bold uppercase tracking-[0.15em] text-[#8fc1ff]">Keep exploring</p><div className="mt-5 space-y-5">{related.map((item) => <Link key={item.slug} href={`/community/${item.slug}`} className="group block border-t border-[#3c3c3c] pt-5 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-white"><p className="text-sm font-semibold leading-5 text-white transition-colors group-hover:text-[#8fc1ff]">{item.title}</p><span className="mt-3 inline-flex items-center gap-1 font-mono text-[9px] uppercase tracking-[0.12em] text-[#bbbbbb]">Read thread <ArrowRight className="h-3 w-3" aria-hidden /></span></Link>)}</div></div></aside>
        </div>
      </div>
    </main>
  );
}
