"use client";

import Link from "next/link";
import { useState } from "react";
import { ArrowLeft, ArrowRight, Bookmark, CheckCircle2, Heart, MessageCircle, Send, Share2 } from "lucide-react";
import { communityPosts, type CommunityPost } from "@/data/community";

const replies = [
  { initials: "SA", name: "Sara Ahmed", role: "Design technologist", time: "12 min ago", body: "The idea of making the review ritual small enough to repeat is the part I am taking away. Security guidance is only useful when it survives a busy week." },
  { initials: "LM", name: "Leo Martins", role: "Cloud architect", time: "7 min ago", body: "Would love to see the threat-model template you used. We have been trying to keep it close to the pull request without making the PR unreadable." },
  { initials: "AK", name: "Ayesha Khan", role: "Product engineer", time: "2 min ago", body: "Absolutely. I added a lightweight version below the post. The key is to record the decision and the residual risk, not produce a perfect document." },
];

function SmallAvatar({ initials }: { initials: string }) {
  return <span className="inline-flex h-10 w-10 shrink-0 items-center justify-center rounded-full bg-[#1c69d4] font-mono text-[10px] font-bold text-white">{initials}</span>;
}

export default function CommunityPostView({ post }: { post: CommunityPost }) {
  const [liked, setLiked] = useState(false);
  const [saved, setSaved] = useState(false);
  const [comment, setComment] = useState("");
  const [commentSent, setCommentSent] = useState(false);

  const related = communityPosts.filter((item) => item.slug !== post.slug).slice(0, 2);

  return (
    <main className="bg-[#f3f0ee] text-[#141413]">
      <div className="mx-auto max-w-[1200px] px-5 py-10 sm:px-6 sm:py-16">
        <Link href="/community" className="inline-flex min-h-10 items-center gap-2 font-mono text-[10px] font-bold uppercase tracking-[0.12em] text-[#6a6a6a] transition hover:text-[#1c69d4] focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-[#1c69d4]"><ArrowLeft className="h-3.5 w-3.5" aria-hidden /> Back to community</Link>
        <div className="mt-10 grid gap-12 lg:grid-cols-[minmax(0,760px)_280px] lg:gap-20">
          <article>
            <div className="flex flex-wrap items-center gap-2 font-mono text-[10px] font-bold uppercase tracking-[0.12em] text-[#1c69d4]"><span>{post.category}</span><span className="text-[#9a9a96]">/</span><span className="text-[#8a8986]">{post.time}</span>{post.solved ? <span className="ml-1 inline-flex items-center gap-1 border border-[#b9d5c2] bg-[#f2f8f3] px-2 py-1 text-[#26733b]"><CheckCircle2 className="h-3 w-3" aria-hidden /> Solved</span> : null}</div>
            <h1 className="mt-5 max-w-4xl text-[clamp(2.25rem,5vw,4.75rem)] font-semibold leading-[0.98] tracking-[-0.065em]">{post.title}</h1>
            <div className="mt-7 flex items-center gap-3 border-b border-[#e2ded9] pb-7"><SmallAvatar initials={post.initials} /><div><p className="text-sm font-semibold">{post.author}</p><p className="mt-0.5 text-xs text-[#6a6a6a]">{post.role}</p></div></div>
            <div className="prose prose-neutral mt-8 max-w-none text-[16px] leading-8 text-[#3a3a38]"><p>{post.excerpt}</p><p>Good work is often less about having one perfect answer and more about building a useful way to make the next decision. This conversation is a place to share the context, trade-offs, and practical details that usually get left out of the final launch note.</p><blockquote className="border-l-2 border-[#1c69d4] bg-[#fcfbfa] px-5 py-4 text-[#141413]">“The best systems make the safe path the easy path.”</blockquote><p>Use the replies to add examples, challenge assumptions, or share a different route. Keep client information and credentials out of the thread so the room stays safe for everyone.</p></div>
            <div className="mt-8 flex flex-wrap items-center gap-2 border-y border-[#e2ded9] py-4"><button type="button" onClick={() => setLiked((value) => !value)} className={`inline-flex min-h-10 items-center gap-2 border px-3 text-xs transition focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-[#1c69d4] ${liked ? "border-[#e22718] bg-[#fff5f4] text-[#e22718]" : "border-[#d8d4d1] text-[#5a5a5a] hover:border-[#e22718] hover:text-[#e22718]"}`}><Heart className="h-4 w-4" fill={liked ? "currentColor" : "none"} aria-hidden /> {post.likes + (liked ? 1 : 0)}</button><button type="button" onClick={() => setSaved((value) => !value)} className={`inline-flex min-h-10 items-center gap-2 border px-3 text-xs transition focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-[#1c69d4] ${saved ? "border-[#1c69d4] bg-[#eef5ff] text-[#1c69d4]" : "border-[#d8d4d1] text-[#5a5a5a] hover:border-[#1c69d4] hover:text-[#1c69d4]"}`}><Bookmark className="h-4 w-4" fill={saved ? "currentColor" : "none"} aria-hidden /> {saved ? "Saved" : "Save"}</button><button type="button" className="inline-flex min-h-10 items-center gap-2 border border-[#d8d4d1] px-3 text-xs text-[#5a5a5a] transition hover:border-[#1c69d4] hover:text-[#1c69d4] focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-[#1c69d4]"><Share2 className="h-4 w-4" aria-hidden /> Share</button><span className="ml-auto hidden items-center gap-2 text-xs text-[#6a6a6a] sm:inline-flex"><MessageCircle className="h-4 w-4" aria-hidden /> {post.replies} replies</span></div>

            <section id="replies" className="mt-12 scroll-mt-24"><div className="flex items-center justify-between"><div><p className="font-mono text-[10px] font-bold uppercase tracking-[0.14em] text-[#1c69d4]">The room responds</p><h2 className="mt-2 text-2xl font-semibold tracking-[-0.03em]">{post.replies} replies</h2></div><MessageCircle className="h-5 w-5 text-[#6a6a6a]" aria-hidden /></div><div className="mt-7 space-y-7">{replies.map((reply) => <div key={`${reply.name}-${reply.time}`} className="flex gap-3.5 border-b border-[#e2ded9] pb-7"><SmallAvatar initials={reply.initials} /><div><div className="flex flex-wrap items-baseline gap-x-2 gap-y-1"><span className="text-sm font-semibold">{reply.name}</span><span className="text-xs text-[#6a6a6a]">{reply.role}</span><span className="font-mono text-[10px] uppercase tracking-[0.08em] text-[#9a9a96]">{reply.time}</span></div><p className="mt-2 text-sm leading-6 text-[#3a3a38]">{reply.body}</p></div></div>)}</div><form className="mt-8 border border-[#d8d4d1] bg-[#fcfbfa] p-4" onSubmit={(event) => { event.preventDefault(); if (comment.trim()) { setCommentSent(true); setComment(""); } }}><label htmlFor="reply" className="font-mono text-[10px] font-bold uppercase tracking-[0.12em] text-[#5a5a5a]">Add to the conversation</label><div className="mt-3 flex flex-col gap-3 sm:flex-row"><textarea id="reply" value={comment} onChange={(event) => { setCommentSent(false); setComment(event.target.value); }} rows={3} placeholder="Share a useful perspective..." className="min-h-[76px] flex-1 resize-y border border-[#d8d4d1] bg-white px-3 py-2 text-sm leading-6 outline-none placeholder:text-[#9a9a96] focus:border-[#1c69d4] focus:ring-2 focus:ring-[#1c69d4]/15" /><button type="submit" className="inline-flex min-h-11 items-center justify-center gap-2 bg-[#141413] px-4 font-mono text-[10px] font-bold uppercase tracking-[0.1em] text-white transition hover:bg-[#1c69d4] focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-[#1c69d4] sm:self-end"><Send className="h-3.5 w-3.5" aria-hidden /> Reply</button></div>{commentSent ? <p className="mt-3 text-xs text-[#26733b]">Your reply is saved as a draft for this preview.</p> : null}</form></section>
          </article>
          <aside className="space-y-8 lg:pt-24"><div className="border border-[#d8d4d1] bg-[#fcfbfa] p-5"><p className="font-mono text-[10px] font-bold uppercase tracking-[0.14em] text-[#1c69d4]">In this thread</p><div className="mt-5 space-y-4 text-sm"><div className="flex items-center justify-between border-t border-[#e2ded9] pt-3"><span className="text-[#6a6a6a]">Reads</span><span className="font-mono text-xs">{post.views.toLocaleString()}</span></div><div className="flex items-center justify-between border-t border-[#e2ded9] pt-3"><span className="text-[#6a6a6a]">Replies</span><span className="font-mono text-xs">{post.replies}</span></div><div className="flex items-center justify-between border-t border-[#e2ded9] pt-3"><span className="text-[#6a6a6a]">Tags</span><span className="max-w-[130px] text-right text-xs">{post.tags.join(" · ")}</span></div></div></div><div><p className="font-mono text-[10px] font-bold uppercase tracking-[0.14em] text-[#1c69d4]">Keep exploring</p><div className="mt-4 space-y-4">{related.map((item) => <Link key={item.slug} href={`/community/${item.slug}`} className="group block border-t border-[#e2ded9] pt-4 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-[#1c69d4]"><p className="text-sm font-semibold leading-5 transition-colors group-hover:text-[#1c69d4]">{item.title}</p><span className="mt-2 inline-flex items-center gap-1 font-mono text-[9px] uppercase tracking-[0.1em] text-[#6a6a6a]">Read thread <ArrowRight className="h-3 w-3" aria-hidden /></span></Link>)}</div></div></aside>
        </div>
      </div>
    </main>
  );
}
