"use client";

import Link from "next/link";
import { useMemo, useState } from "react";
import { ArrowLeft, ArrowRight, MapPin, MessageCircle, Search, Users, X } from "lucide-react";
import { communityMembers, type CommunityMember } from "@/data/community";

export default function CommunityMembersView() {
  const [query, setQuery] = useState("");
  const [selected, setSelected] = useState<CommunityMember | null>(null);

  const filteredMembers = useMemo(() => {
    const normalized = query.trim().toLowerCase();
    if (!normalized) return communityMembers;
    return communityMembers.filter((member) => [member.name, member.role, member.location, member.specialty, member.bio].join(" ").toLowerCase().includes(normalized));
  }, [query]);

  return (
    <main className="bg-black text-white">
      <div className="m-stripe" aria-hidden="true" />
      <div className="mx-auto max-w-[1440px] px-5 py-12 sm:px-8 sm:py-20 lg:px-12">
        <Link href="/community" className="inline-flex min-h-11 items-center gap-2 font-mono text-[10px] font-bold uppercase tracking-[0.14em] text-[#bbbbbb] transition hover:text-white focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-white"><ArrowLeft className="h-3.5 w-3.5" aria-hidden /> Back to community</Link>
        <div className="mt-14 max-w-4xl"><div className="flex items-center gap-3 font-mono text-[10px] font-bold uppercase tracking-[0.16em] text-[#bbbbbb]"><span className="h-px w-8 bg-[#1c69d4]" /> The people behind the posts</div><h1 className="mt-6 text-[clamp(3rem,8vw,6.5rem)] font-bold uppercase leading-[0.94] tracking-[-0.04em] text-white">Meet the<br /><span className="text-[#8fc1ff]">community.</span></h1><p className="mt-8 max-w-2xl text-base font-light leading-7 text-[#bbbbbb] sm:text-lg">Different disciplines. Different time zones. The same curiosity about making useful things with care.</p></div>
        <div className="mt-14 grid gap-3 sm:grid-cols-[minmax(0,1fr)_auto]"><label className="flex h-12 items-center gap-3 border border-[#3c3c3c] bg-[#1a1a1a] px-4 text-[#7e7e7e] focus-within:border-white"><Search className="h-4 w-4" aria-hidden /><span className="sr-only">Search members</span><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search by name, role, or specialty" className="min-w-0 flex-1 bg-transparent text-sm font-light text-white outline-none placeholder:text-[#7e7e7e]" /></label><div className="inline-flex min-h-12 items-center justify-center gap-2 border border-[#3c3c3c] px-5 font-mono text-[10px] font-bold uppercase tracking-[0.14em] text-[#bbbbbb]"><Users className="h-4 w-4" aria-hidden /> {filteredMembers.length} profiles</div></div>
        <div className="mt-10 grid gap-px border border-[#3c3c3c] bg-[#3c3c3c] sm:grid-cols-2 lg:grid-cols-3">{filteredMembers.map((member) => <article key={member.name} className="bg-[#1a1a1a] p-6 transition hover:bg-[#262626] sm:p-7"><div className="flex items-start justify-between"><button type="button" onClick={() => setSelected(member)} aria-label={`View ${member.name}'s profile`} className="inline-flex h-14 w-14 items-center justify-center rounded-full font-mono text-sm font-bold text-white focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-white" style={{ background: member.accent }}>{member.initials}</button><span className="flex items-center gap-2 font-mono text-[9px] uppercase tracking-[0.12em] text-[#0fa336]"><span className="h-2 w-2 rounded-full bg-[#0fa336]" /> Active</span></div><button type="button" onClick={() => setSelected(member)} className="mt-7 text-left focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-white"><h2 className="text-xl font-bold uppercase tracking-[-0.02em] text-white">{member.name}</h2><p className="mt-2 text-sm font-light text-[#bbbbbb]">{member.role}</p><p className="mt-4 text-sm font-light leading-6 text-[#bbbbbb]">{member.bio}</p></button><div className="mt-6 space-y-3 border-t border-[#3c3c3c] pt-5 text-xs font-light text-[#bbbbbb]"><p className="flex items-center gap-2"><MapPin className="h-3.5 w-3.5 text-[#8fc1ff]" aria-hidden />{member.location}</p><p className="flex items-center gap-2"><MessageCircle className="h-3.5 w-3.5 text-[#8fc1ff]" aria-hidden />{member.specialty}</p></div><div className="mt-6 flex items-center justify-between"><span className="font-mono text-[10px] uppercase tracking-[0.1em] text-[#7e7e7e]">{member.contribution}</span><Link href="/community" className="inline-flex min-h-10 items-center gap-1 font-mono text-[10px] font-bold uppercase tracking-[0.12em] text-white transition hover:text-[#8fc1ff]">View posts <ArrowRight className="h-3 w-3" aria-hidden /></Link></div></article>)}</div>
        {filteredMembers.length === 0 ? <div className="border border-dashed border-[#3c3c3c] p-12 text-center"><Search className="mx-auto h-6 w-6 text-[#7e7e7e]" aria-hidden /><p className="mt-4 font-semibold text-white">No profiles found</p><p className="mt-2 text-sm font-light text-[#bbbbbb]">Try searching by a shorter name, role, or specialty.</p></div> : null}
        <div className="mt-16 border border-[#3c3c3c] bg-[#1a1a1a] p-7 sm:flex sm:items-center sm:justify-between sm:p-10"><div><p className="font-mono text-[10px] font-bold uppercase tracking-[0.15em] text-[#8fc1ff]">Your perspective belongs here</p><p className="mt-3 max-w-2xl text-2xl font-bold uppercase leading-tight tracking-[-0.03em] text-white">The best communities are shaped by people willing to share the unfinished version.</p></div><Link href="/community" className="mt-7 inline-flex min-h-12 shrink-0 items-center gap-2 border border-white px-5 font-mono text-[10px] font-bold uppercase tracking-[0.14em] text-white transition hover:bg-white hover:text-black focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-white sm:mt-0">Join the conversation <ArrowRight className="h-3.5 w-3.5" aria-hidden /></Link></div>
      </div>
      {selected ? <div className="fixed inset-0 z-50 flex items-end justify-center bg-black/80 p-0 sm:items-center sm:p-6" role="dialog" aria-modal="true" aria-labelledby="member-dialog-title"><div className="w-full max-w-lg border border-[#3c3c3c] bg-[#1a1a1a] p-6 sm:p-8"><div className="flex items-start justify-between gap-4"><div className="flex items-center gap-4"><span className="inline-flex h-12 w-12 items-center justify-center rounded-full font-mono text-xs font-bold text-white" style={{ background: selected.accent }}>{selected.initials}</span><div><h2 id="member-dialog-title" className="text-xl font-bold uppercase text-white">{selected.name}</h2><p className="mt-1 text-sm font-light text-[#bbbbbb]">{selected.role}</p></div></div><button type="button" onClick={() => setSelected(null)} aria-label="Close profile" className="inline-flex h-11 w-11 items-center justify-center border border-[#3c3c3c] text-[#bbbbbb] transition hover:border-white hover:text-white"><X className="h-5 w-5" aria-hidden /></button></div><p className="mt-7 text-sm font-light leading-7 text-[#bbbbbb]">{selected.bio}</p><div className="mt-6 space-y-3 border-t border-[#3c3c3c] pt-5 text-sm font-light text-[#bbbbbb]"><p className="flex items-center gap-2"><MapPin className="h-4 w-4 text-[#8fc1ff]" aria-hidden />{selected.location}</p><p className="flex items-center gap-2"><MessageCircle className="h-4 w-4 text-[#8fc1ff]" aria-hidden />{selected.specialty}</p><p className="font-mono text-[10px] uppercase tracking-[0.12em] text-[#7e7e7e]">{selected.joined} · {selected.contribution}</p></div></div></div> : null}
    </main>
  );
}
